services:
  db:
    image: mariadb:10.6
    volumes:
      - db:/var/lib/mysql
    restart: no
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: no
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
volumes:
  db: